name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Inicializar Terraform
        run: terraform init

      - name: Validar configuración
        run: terraform validate

      - name: Planificar cambios
        run: terraform plan -var-file="terraform.tfvars"
